name: cd

on:
  push:
    branches:
      - "main"
      - "setup-cd"

jobs:
  deploy-gridle:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # This example uses the docker login action
      - uses: "docker/login-action@v1"
        with:
          registry: "us-central1-docker.pkg.dev" # or REGION-docker.pkg.dev
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:gridle_game"
          tags: us-central1-docker.pkg.dev/geography-games/gridle-repo/gridle:latest

      - id: deploy
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: gridle
          image: us-central1-docker.pkg.dev/geography-games/gridle-repo/gridle:latest
